--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RADICALES
--------------------------------------------------------

  CREATE TABLE "HR"."RADICALES" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"DNI_ULTRA" NUMBER, 
	"FECHA_NACI" DATE, 
	"AFICION_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "HR"."RADICALES"."NOMBRE" IS 'nombre de los ultras';
   COMMENT ON COLUMN "HR"."RADICALES"."DNI_ULTRA" IS 'dni de los ultras';
   COMMENT ON COLUMN "HR"."RADICALES"."FECHA_NACI" IS 'fecha de nacimiento';
   COMMENT ON COLUMN "HR"."RADICALES"."AFICION_ID" IS 'clave ajena';
--------------------------------------------------------
--  DDL for Index RADICALES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."RADICALES_PK" ON "HR"."RADICALES" ("DNI_ULTRA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table RADICALES
--------------------------------------------------------

  ALTER TABLE "HR"."RADICALES" ADD CONSTRAINT "RADICALES_PK" PRIMARY KEY ("DNI_ULTRA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HR"."RADICALES" MODIFY ("FECHA_NACI" NOT NULL ENABLE);
  ALTER TABLE "HR"."RADICALES" MODIFY ("DNI_ULTRA" NOT NULL ENABLE);
  ALTER TABLE "HR"."RADICALES" MODIFY ("NOMBRE" NOT NULL ENABLE);
